
// $scope.course = [
// 	{'id': 1, 'name': 'BS Computer Science', 'value':'BSCS'},
// 	{'id': 2, 'name': 'BS Business Administration', 'value': 'BSBA'},
// 	{'id': 3, 'name': 'BS Office Administration', 'value': 'BSBM'}
// ];

// $scope.major = [
// 	{'id': 1, 'course': 'BSCS', 'name': 'Hardware', 'value':'Hardware'},
// 	{'id': 1, 'course': 'BSCS', 'name': 'Software', 'value':'Software'},
// 	{'id': 1, 'course': 'BSCS', 'name': 'CHS', 'value':'CHS'},
// 	{'id': 2, 'course': 'BSBA', 'name': 'Marketing', 'value': 'Marketing'},
// 	{'id': 2, 'course': 'BSBA', 'name': 'Management', 'value': 'Management'},
// 	{'id': 3, 'course': 'BSBM', 'name': 'Steno', 'value': 'Steno'},
// 	{'id': 3, 'course': 'BSBM', 'name': 'Office Management', 'value': 'Office Management'}
// ];

$scope.gender = [
	{'id': 1, 'name': 'Male', 'value': 'M'},
	{'id': 2, 'name': 'Female', 'value': 'F'},
	{'id': 3, 'name': 'Others', 'value': 'O'}
];

$scope.civilstatus = [
	{'id': 1, 'name': 'Single','value': 'S'},
	{'id': 2, 'name': 'Married', 'value': 'M'},
	{'id': 3, 'name': 'Widow', 'value': 'W'},
	{'id': 4, 'name': 'Others', 'value': 'O'}
];

$scope.position = [
	{'id': 1, 'name': 'President', 'value': 'President'},
	{'id': 2, 'name': 'Vice President', 'value': 'Vice President'},
	{'id': 3, 'name': 'Secretary', 'value': 'Secretary'},
	{'id': 4, 'name': 'Treasurer', 'value': 'Treasurer'},
	{'id': 5, 'name': 'Peace In Order', 'value': 'Peace In Order'},
	{'id': 6, 'name': 'Auditor', 'value': 'Auditor'}
];

$scope.partylist = [
	{'id': 1, 'name': 'DD Squad', 'value':'DDS'},
	{'id': 2, 'name': 'Liberal Party', 'value':'LP'},
	{'id': 3, 'name': 'United Alliance', 'value':'UNA'},
	{'id': 4, 'name': 'Magdalo Party', 'value':'MGDL'},
	{'id': 5, 'name': 'Independent', 'value':'IND'}
];

$scope.entrytype = [
	{'id': 1, 'name': 'Professor'},
	{'id': 2, 'name': 'Student'}
];

$scope.entryStatus = [
	{'id': 1, 'name': 'Regular', 'value': 'REG'},
	{'id': 2, 'name': 'Iregular', 'value': 'IREG'},
];